### ISSUE TITLE
Disc Dumping to USB issue (FAT32/NTFS)

### ISSUE THREAD

**Issue by 60fpshacksrock** [Zarh/ManaGunZ#62] opened 2021-07-19 13:45 UTC
I am unsure if this has been mentioned before or if anyone else has tried and had the same issue.

I cannot say about 1.38 because I could never get it to show what disc was in the disc drive in the game list.

1.39 and 1.40 recognize the disc and will allow me to dump to to both HDD and USB. Dumping to HDD is fine, and I also noticed unlike another dumping tool (multiMAN) MG will allow the disc to continue being dumped even when DRE's are detected and I must say thank you for this. 

The problem seems to be USB-exclusive. When dumping a disc (ISO) to it, even with a disc that is good and would fully copy to the HDD. The problem is that every now and then it will say 0 bytes copy speed. I am guessing this may be because dumping to USB is not as fast as the HDD. I thought maybe it was just saying that so I ignored it. 

I then proceeded to play Gran Turismo 6 and, as you may know this game has an option to install to HDD as you play. Well, I turned that of as it is not needed because the reading from a USB drive is almost as fast as HDD. Then I went to the car dealership area and I noticed all of the car dealership would not load. They had blank icons.

At first I though this was just a bug with the game. Turns out it happened again. So, I deleted the game and then dumped to HDD and then used the file manager in IRISMAN to copy to USB just be safe. No more problems after that.

So yes, I think it may be a bottleneck with the USB speed. I know that NTFS even on a flash drive has a bit more write speed but that does not seem to matter.

**Comment by foliage-burner** [comment] 2021-07-19 15:57
1. Disc dumping/detection was added on v1.39, so the disc not showing up in v1.38 is perfectly normal.
2. Could you verify your initial dump to USB with an IRD file? It may be that some file is getting corrupted in the process (or maybe your USB is failing). You can verify it straight from MGZ, or you can use PS3-ISO-Rebuilder on PC.
3. The fact that ManaGunZ ignores disc reading errors is more of a bug than a feature. If there are parts of a game MGZ can't read, then a file in the resulting ISO has a high chance of being corrupted. I guess being able to have a corrupted dump may be valuable to some people, but it can lead to errors. (Redump related issue: http://forum.redump.org/post/92149/#p92149). There is also a chance (due to this) that MGZ is generating incorrect IRD files and uploading them to its server, which would be bad for future verfication of games.

**Comment by Zarh** [comment] 2021-07-19 18:40
Indeed, it would be better to do like multiMAN

**Comment by 60fpshacksrock** [comment] 2021-07-19 20:39
As I said before, no issues when dumping to HDD.

Also, it isn't just a file per se, this happens with other games too.

**Comment by Zarh** [comment] 2021-07-19 20:48
I'll try something, then I'll pull another pre-release. Will you be able to tell me if it's fixed ?

**Comment by 60fpshacksrock** [comment] 2021-07-19 21:10
I will test it, yes.

**Comment by Zarh** [comment] 2021-07-19 23:50
Can you check with this one, please : https://github.com/Zarh/ManaGunZ/releases/tag/1.41
(I'm not sure if it's going to fix your issue)

**Comment by 60fpshacksrock** [comment] 2021-07-20 16:42
File manger is still locking up when attempting to exit.

File system on the USB is FAT32. Not sure if it matters or not but when I exit I press the circle button
multiple times instead of holding it.

As of this post I am dumping the smallest game I own to my NTFS drive: Beowulf.

**Comment by 60fpshacksrock** [comment] 2021-07-20 17:33
Finished dumping.

I downloaded PS3 ISO Rebuilder 1.0.4.1 and it checked the game/IRD and it says all of the files are valid.

**Comment by Zarh** [comment] 2021-07-21 19:03
Do you think the issue is definitely fixed ? (this one: https://github.com/Zarh/ManaGunZ/issues/62#issue-947670977)

**Comment by 60fpshacksrock** [comment] 2021-07-22 01:15
I think so.

**Comment by Bigmanjapan** [comment] 2021-07-22 06:26
I'm not sure if it's warranted to create a separate issue, therefore I'll write it here.

If you're going to implement decryption key dumping (what GetKey does), could you make the output files have unique filenames? In a similar fashion to how ManaGunZ assigns filenames to the dumped ISOs. For example: BCES01335_20210710_063641.iso. 

The issue is that when people want to dump many games in one sitting via GetKey, they have to enter file manager and transfer output files to their PC after each dump since GetKey always names the files with the same filenames (and therefore overwrites them with each new dump):

1. disc.pic
2. getkey.log

If you could make your program assign unique filenames, that would allow users to dump their games much faster.

**Comment by Zarh** [comment] 2021-07-22 10:39
Thank you very much.
I'll close this issue, I'll fix the issue #61 before the 1.41 release.

**Closed** 2021-07-22 10:40 UTC
