### ISSUE TITLE
[IRD] Wrong game name

### ISSUE THREAD

**Issue by jhonathanc** [Zarh/ManaGunZ#51] opened 2021-05-05 23:06 UTC
Games with digital manual has wrong IRD creation. It's getting the name from PARAM.SFO of the manual instead of the PARAM.SFO of the game.
eg.: BCUS98254_20210505_224318.ird

Probably you will face the same situation with games that has PS3_EXTRA folder. The only I remember you can try is Borderlands 2 GOTY, but I don't have the discs anymore to check how IRD is created (yes, it has 2 discs, one of the game and other of extras).

Edit.: Yes, you will face the same issue. I also checked that ManaGunZ is displaying the wrong name for this games, getting the name of the wrong PARAM.SFO for discs (on ISO, it shows the correct name).

![ManaGunZ](https://user-images.githubusercontent.com/36962629/117221483-bd4a2f80-addf-11eb-83ff-1ddf12e4a113.png)

**Comment by foliage-burner** [comment] 2021-06-11 19:53
@Zarh, I can confirm that the wrong title is being displayed when a game includes a manual (It's happened to me with a later version of inFamous 2 [being read straight from Bluray], which includes a digital game manual from the inFamous Collection). I haven't looked at the code (yet*), but I assume this is happening because Mangunz looks recursively for a param.sfo in the rip / bluray-disc (I guess to add support to games which are stored in multiple subfolders). If this is the case, the search for a param.sfo could be made more strict, and be made to check whether the .sfo file is directly inside the PS3_GAME folder. Another solution could be to drop support for multiple subfolders, though that would not be ideal.

*_Sometimes foreshadowing is relatively obvious._

**Comment by Zarh** [comment] 2021-06-12 12:44
It read the param.sfo inside PS3_GAME/PKGDIR/param.sfo instead of PS3_GAME/param.sfo . In the next update it will read only PS3_GAME/param.sfo

I wrote it like that because some game don't display the name of the game in the first PS3_GAME/param.sfo, it's written 'Install Disc". I have one like this. I didn't think manuals use the same directory. 

In the next update I removed it will read only PS3_GAME/param.sfo for 2 reasons : 
- manuals use the same directory
- IRD use only PS3_GAME/param.sfo

I'll probably do something to display the extra content of a backup name of the backup (because I don't like display only 'install disc'). AFAIK, the extra contents are inside these folder : PKGDIR/PS3_GMXX/PK3_EXTRA/INSDIR . It's in my todo list, but I still don't know how, i'm going to display them.

**Comment by Zarh** [comment] 2021-06-12 13:31
it's fixed now : https://github.com/Zarh/ManaGunZ/releases/tag/1.40

**Closed by Zarh** 2021-06-12 13:31 UTC

**Comment by foliage-burner** [comment] 2021-06-26 19:46
An idea to better display 'Install Disc' games: If you detect that the name in PS3_GAME/param.sfo is 'Install Disc', look for PS3_GAME/PKGDIR/param.sfo, get the name of the pkg. Then, display something on the UI like 

"<PKGDIR Title><0x0A>(Install Disc)"

So that the "Install Disc" phrase is shown in a new line (I believe ManGunZ does support that from what I tested). If this doesn't look good to you, you could try writing out "Install Disc" in utf-8 capital small letters, if they are supported inside ManaGunZ, so that it looks like "ɪɴꜱᴛᴀʟʟ ᴅɪꜱᴄ" (XMB doesn't support these small capital letters, though).

Displaying 'Install Disc' in a similar way that XMB handles subtitle (like in save data) might look good too, though it will probably require more work to implement.
